
name: Create Repository Test Workflow

on:
  workflow_dispatch:
    
    inputs:
      repo_owner:
        description: Owner of the repository to be created
        default: ndupoiron-org
        type: string
      
      repo_name:
        description: Name of the repository to create
        type: string
        required: true
        
      repo_visibility:
        description: can be public or private
        type: string
        default: public

jobs:
  create_repo:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
    
    - name: Create repository
      uses: ndupoiron-ops/boostrap@main
      with:
        repo_owner: ${{ github.event.inputs.repo_owner }}
        repo_name: ${{ github.event.inputs.repo_name }}
        repo_visibility: ${{ github.event.inputs.repo_visibility }}
        token: ${{ secrets.REPO_OPS_TOKEN }}
